#!/bin/bash

# Copyright (C) 2016 Paul Kocialkowski <contact@paulk.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

PARABOLA_RELEASE="/etc/parabola-release"
PACMAN_CONF="pacman.conf"
PACKAGES="packages"
MACHINE="machine"
ARCHS="archs"

parabola_archs() {
	project_file_contents "$project" "$CONFIGS" "$ARCHS"
}

parabola_arch_match() {
	local archs=$( parabola_archs )
	local machine_local=$( uname -m )
	local machine_path

	for arch in $archs
	do
		machines=$( project_file_contents "$project" "$CONFIGS" "$MACHINE" "$arch" )

		for machine in $machines
		do
			if [ "$machine" = "$machine_local" ]
			then
				echo "$arch"
				return
			fi
		done
	done
}

parabola_host_check() {
	file_exists_check "$PARABOLA_RELEASE"
}

parabola_pacman_config_path() {
	project_file_path "$project" "$CONFIGS" "$PACMAN_CONF" "$@"
}

parabola_packages() {
	project_file_contents_herit "$project" "$CONFIGS" "$PACKAGES" "$@" | tr '\n' ' '
}
