#!/bin/bash

# Copyright (C) 2016-2018 Paul Kocialkowski <contact@paulk.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

install() {
	local install_path=$( project_install_path "$project" )
	local paper_scripts_install_path=$( project_install_path "paper-scripts" )

	project_action "install" "paper-scripts"

	project_install "$project"

	cp "$paper_scripts_install_path/common" "$install_path/"
}

install_check() {
	project_install_check "$project"
}

release() {
	project_release_install_archive "$project" "$TOOLS"
}

release_check() {
	project_release_install_archive_check "$project" "$TOOLS"
}

clean() {
	project_clean "$project"
}
