#!/bin/bash

# Copyright (C) 2016 Paul Kocialkowski <contact@paulk.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

WIFIVERSION="wifiversion"
CONFIG="config"
ARCH="arch"

linux_cros_arch() {
	project_file_contents "$project" "$CONFIGS" "$ARCH" "$@"
}

linux_cros_config_path() {
	project_file_path "$project" "$CONFIGS" "$CONFIG" "$@"
}

linux_cros_wifiversion() {
	project_file_contents "$project" "$CONFIGS" "$WIFIVERSION" "$@"
}

linux_cros_target() {
	local arch=$1

	case $arch in
	"arm")
		echo "zImage"
		;;
	"arm64")
		echo "Image"
		;;
	*)
		return 1
	esac
}
