#!/bin/bash

# Copyright (C) 2016-2018 Paul Kocialkowski <contact@paulk.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

usage() {
	printf "$executable [action] [storage] [kernel files] [rootfs medium]\n" >&2

	printf "\nActions:\n" >&2
	printf "  install - Install cros-prepared kernel from kernel files for the medium to storage\n" >&2

	usage_storage_common

	printf "\nEnvironment variables:\n" >&2
	usage_variables_storage
	printf "  VBOOT_TOOLS_PATH - Path to vboot tools\n" >&2
}

storage_kernel_partition_index() {
	local storage_path=$1

	cgpt find -t kernel "$storage_path" | head -n 1 | sed "s/.*[a-z]//g"
}

storage_rootfs_partition_index() {
	local storage_path=$1

	cgpt find -t rootfs "$storage_path" | head -n 1 | sed "s/.*[a-z]//g"
}

install() {
	local storage_path=$1
	local kernel_files_path=$2
	local rootfs_medium=$3

	local kernel_partition_index=$( storage_kernel_partition_index "$storage_path" )
	local rootfs_partition_index=$( storage_rootfs_partition_index "$storage_path" )

	kernel_install_partition "$storage_path" "$kernel_files_path" "$rootfs_medium" "$kernel_partition_index" "$rootfs_partition_index"
}

setup() {
	root=$( realpath "$( dirname "$0" )" )
	executable=$( basename "$0" )

	source "$root/common"

	if [ -n "$VBOOT_TOOLS_PATH" ]
	then
		PATH="$PATH:$VBOOT_TOOLS_PATH"
	fi
}

cros_kernel_setup() {
	local action=$1
	local storage_path=$2
	local kernel_files_path=$3
	local rootfs_medium=$4

	set -e

	setup "$@"

	if [ -z "$action" ] || [ -z "$storage_path" ] || [ -z "$kernel_files_path" ] || [ -z "$rootfs_medium" ]
	then
		usage
		exit 1
	fi

	case $action in
	"install")
		requirements "cgpt"
		install "$storage_path" "$kernel_files_path" "$rootfs_medium"
		;;
	*)
		usage
		exit 1
		;;
	esac
}

cros_kernel_setup "$@"
